### ISSUE TITLE
Asynchronous 

### ISSUE THREAD

**Issue by YoungTrep** [starsflower/py18n#1]
I tried using `py18n` for a discord bot with `motor` but I was unable to do the get locale function because it isn’t asynchronous so would you help me get around this error or if it is on your side, may you fix it?

**Comment by mwja** [comment]
Hey there @YoungTrep, I was on holiday so didn't see your request sorry!

Do you mean to say that you need the get_locale function to be asynchronous, while `py18n` expects a synchronous function?

**Comment by YoungTrep** [comment]
@starsflower It's fine and yeah that's what I'm trying to say

**Comment by mwja** [comment]
You could either wrap your async function in the sync function...

```python
import asyncio

#...

def get_locale(ctx):
    return asyncio.run(my_get_locale_function(ctx))
```

Or if it's a really big issue, I can look into adding native support for it.

**Comment by YoungTrep** [comment]
thank you I will look into using asyncio and I will let you know if it works or not
